PAYMENT_METHOD_CASH = 1
PAYMENT_METHOD_TRANSFER = 2

PAYMENT_METHODS = {
    PAYMENT_METHOD_CASH: 'Cash',
    PAYMENT_METHOD_TRANSFER: 'Bank transfer',
}

DAYS = 1
WEEKS = 2
MONTHS = 3

TIME_UNIT_CHOICES = {
    DAYS: 'Days',
    WEEKS: 'Weeks',
    MONTHS: 'Months',
}
