version: '2'

services:
  postgres:
    image: postgres:11
    container_name: col-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${USER}

  redis:
    image: redis:5
    container_name: col-redis
    ports:
      - "6379:6379"
