# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.TextField()),
                ('phone', models.TextField()),
                ('relation', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_name', models.TextField()),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='GeneralSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(null=True, blank=True)),
                ('days_to_vote_since_membership', models.PositiveIntegerField()),
                ('minimum_age_to_vote', models.PositiveIntegerField()),
                ('vote_allowed_permanently', models.BooleanField()),
                ('renewal_month', models.PositiveIntegerField(null=True, blank=True)),
                ('renewal_grace_months_period', models.PositiveIntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('height', models.PositiveIntegerField(null=True, blank=True)),
                ('weight', models.PositiveIntegerField(null=True, blank=True)),
                ('info', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateField()),
                ('form_filled', models.DateField()),
                ('paid', models.DateField(null=True, blank=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('payment_method', models.PositiveIntegerField(choices=[(1, 'Cash'), (2, 'Bank transfer')])),
                ('notes', models.TextField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('postcode', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('participation_form_filled', models.DateField()),
                ('family', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT,
                                             related_name='family_members', to='col.Family')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('base_amount', models.PositiveIntegerField()),
                ('usable_from', models.DateField()),
                ('usable_until', models.DateField(null=True, blank=True)),
                ('can_vote', models.BooleanField()),
                ('expires', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships',
                                    to='col.Participant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='member_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships',
                                    to='col.MemberType'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships',
                                    to='col.Tier'),
        ),
        migrations.AddField(
            model_name='tier',
            name='allowed_member_types',
            field=models.ManyToManyField(to='col.MemberType'),
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_info',
                                    to='col.Participant'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_contacts',
                                    to='col.Participant'),
        ),
    ]
